
[system]
user_name = "admin0"
remote_work_dir = "auto-bencher-workspace"

[jdk]
use_custom_jdk = true # Reserved.
dir_name = "jdk1.8.0_211"
package_path = "package/jdk-8u211-linux-x64.tar.gz"
jvm_args = "-Xmx4g -Xms4g"

[machines]
server = "192.168.1.11"
client = "192.168.1.12"
