
[basic]
"JAR_DIR" = "load"

[vanilladb]
"org.vanilladb.core.storage.buffer.BufferMgr.BUFFER_POOL_SIZE" = "1024 102400"
"org.vanilladb.core.storage.file.io.IoAllocator.USE_O_DIRECT" = "true"

[vanillabench]
"org.vanilladb.bench.BenchmarkerParameters.WARM_UP_INTERVAL" = "5000"
"org.vanilladb.bench.BenchmarkerParameters.BENCHMARK_INTERVAL" = "5000"
"org.vanilladb.bench.BenchmarkerParameters.BENCH_TYPE" = "1"
"org.vanilladb.bench.benchmarks.tpcc.TpccConstants.NUM_WAREHOUSES" = "5"
