
[basic]
"jar.dir" = "load"

[vanilladb]
"org.vanilladb.core.storage.buffer.BufferMgr.BUFFER_POOL_SIZE" = "102400"

[vanillabench]
"org.vanilladb.bench.BenchmarkerParameters.BENCH_TYPE" = "1"
"org.vanilladb.bench.benchmarks.micro.MicrobenchConstants.NUM_ITEMS" = "100000"
