
[auto_bencher]
jar_dir = "load"
server_count = "3"
server_client_ratio = "1"
server_per_machine = "1"
client_per_machine = "2"

[vanilladb]
"org.vanilladb.core.storage.buffer.BufferMgr.BUFFER_POOL_SIZE" = "512000"
"org.vanilladb.core.storage.file.io.IoAllocator.USE_O_DIRECT" = "true"

[vanillabench]
"org.vanilladb.bench.BenchmarkerParameters.BENCH_TYPE" = "2"
"org.vanilladb.bench.benchmarks.tpcc.TpccConstants.NUM_WAREHOUSES" = "5"
